# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Sunburn' do

pod 'REFrostedViewController', '~> 2.4'
pod 'AFNetworking', '~> 2.5.4'
pod 'SDWebImage', '~>3.7'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'
pod 'SpinKit', '~> 1.1'
pod 'THCalendarDatePicker', '~> 1.2.0'
pod 'JTAlertView'

end

target 'SunburnTests' do

end

